<?php

/**
 * @file
 * Contains commerce_interswitch_webpay.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function commerce_interswitch_webpay_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the commerce_interswitch_webpay module.
    case 'help.page.commerce_interswitch_webpay':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Commerce Interswitch WebPay integration payment gateway') . '</p>';
      return $output;

    default:
  }
}
